name: flutter_application_baikiemtra
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0 # Đã chỉnh lại phiên bản ổn định hơn, 3.9.2 có thể chưa phổ biến

dependencies:
  flutter:
    sdk: flutter
  # Các thư viện bổ sung
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Phần cấu hình Flutter
flutter:
  uses-material-design: true
  
  # Khai báo thư mục ảnh (Đảm bảo bạn đã copy thư mục 'anh' vào trong dự án)
  assets:
    - anh/